### ISSUE TITLE
특정 카테고리 선택 후 새로고침 시, All 버튼에 selected style이 적용되는 현상

### ISSUE THREAD

**Issue by hexdrinker** [JaeYeopHan/gatsby-starter-bee#108]
## Description

블로그 메인에서 카테고리를 선택하면 session storage에 카테고리 값이 저장되는걸로 알고있습니다.
전체가 아닌 특정 카테고리 선택 후 새로고침 시, 해당 카테고리 태그 버튼에 selected style이 적용되는 것이 아니라 All 버튼에 selected style이 적용됩니다.

jbee.io 블로그에선 문제 없이 작동하나 제 블로그나 일부 다른 분들 블로그에서는 저와 같이 동작하더군요.
이상한건 제 블로그도 local 환경에서는 문제 없는데 production 환경에서 이런 문제가 발생한다는 점입니다.
원인 또는 문제를 해결할 수 있는 방법이 있을까요?

**Comment by JaeYeopHan** [comment]
@hexdrinker 카테고리 유지를 위해서 현재 선택된 카테고리를 url의 query parameter에서 관리하도록 수정했습니다! 제보 감사합니다~

(ref: https://github.com/JaeYeopHan/JBEE.io/pull/175/files)
