### ISSUE TITLE
Sun/moon icons for light/dark mode 

### ISSUE THREAD

**Issue by M0nica** [JaeYeopHan/gatsby-starter-bee#123]
## Description
I think it would make the theme more internationalized if for the light/dark mode switch the label was a sun/moon icon instead of the letter “l” and “d”. If you agree I’d be interested in working on this. 
![C55106A3-DBAE-4E72-A998-22F3039E2DE7](https://user-images.githubusercontent.com/6998954/81466549-9e02cd00-91a0-11ea-84bf-848e7310b96e.jpeg)
![28D3E087-BD17-4F4F-8196-F8780F8ADE1A](https://user-images.githubusercontent.com/6998954/81466550-9e9b6380-91a0-11ea-8590-594be4832027.jpeg)

**Comment by JaeYeopHan** [comment]
@M0nica Hi! Sounds Good! Please PR! :)

**Comment by M0nica** [comment]
Great, I will work on it soon. Do you have preferred icons for the site? @JaeYeopHan if not I’ll probably use font awesome https://fontawesome.com/ or https://shape.so/.

**Comment by JaeYeopHan** [comment]
Anything! https://shape.so/ looks good!
