### ISSUE TITLE
Field "thumbnail" must not have a selection since type "String" has no subfields.

### ISSUE THREAD

**Issue by snoop2head** [JaeYeopHan/gatsby-starter-bee#171]
Related to #151 

## Deleting [hello.md](https://github.com/JaeYeopHan/gatsby-starter-bee/blob/master/content/blog/development/hello.md) causes GraphQL query error
When [hello.md](https://github.com/JaeYeopHan/gatsby-starter-bee/blob/master/content/blog/development/hello.md) file is deleted, the error message of the following occurs.

```
Failed to compile
There was an error in your GraphQL query:

Field "thumbnail" must not have a selection since type "String" has no subfields.

This can happen if you e.g. accidentally added { } to the field "thumbnail". If you didn't expect "thumbnail" to be of type "String" make sure that your input source and/or plugin is correct.

File: /Users/noopy/noopy/src/templates/blog-post.js
```

Since [hello.md](https://github.com/JaeYeopHan/gatsby-starter-bee/blob/master/content/blog/development/hello.md) is the only file that mandates the 'thumbnail' field, I believe this is the cause of the error. 

Will there any way to resolve this issue?

**Comment by Highjune** [comment]
same.. I cannot solve this problem T.T

**Comment by JaeYeopHan** [comment]
@snoop2head  @Highjune 
i know this issue, but first check your `.md` file.

is there the thumbnails field in the frontmatter?

like this:
```
---
title: 'Test'
date: 2020-8-39 16:21:13
category: 'development'
draft: false
thumbnail: '',
---
```

**Comment by snoop2head** [comment]
@JaeYeopHan 

* System Environment: Mac OS 10.15.5
* npm 6.14 && node 13.11

### Replicating error
1. Created thumbnail field on any existing random post as following. Website functions well after the change:
```
---
title: 'Questions that I were being asked Frequently'
date: 2020-08-19 13:01:13
category: 'data'
draft: true
thumbnail: ' '
---
```

2. Deleted hello.md file. Then it yields the following error message:

```
Failed to compile
There was an error in your GraphQL query:

Field "draft" is not defined by type MarkdownRemarkFrontmatterFilterInput.

File: /Users/noopy/noopy/src/pages/index.js

There was an error in your GraphQL query:

Field "thumbnail" must not have a selection since type "String" has no subfields.

This can happen if you e.g. accidentally added { } to the field "thumbnail". If you didn't expect "thumbnail" to be of type "String" make sure that your input source and/or plugin is correct.

File: /Users/noopy/noopy/src/templates/blog-post.js
```


3. If hello.md file were to restored then website functions well again.


4. If I were to delete any png or gif files included in hello.md file, website crashes as following:
```
There was an error in your GraphQL query:

Field "thumbnail" must not have a selection since type "String" has no subfields.

This can happen if you e.g. accidentally added { } to the field "thumbnail". If you didn't expect "thumbnail" to be of type "String" make sure that your input source and/or plugin is correct.

File: /Users/noopy/noopy/src/templates/blog-post.js
```
### Actions
I am looking into graphql queries, but I can't find which field is causing a problem...

**Comment by JaeYeopHan** [comment]
i removed `thumbnail` field in `blog-post.js` query.
like this:
https://github.com/JaeYeopHan/gatsby-starter-bee/pull/180

😭 
(using default og image...)

**Comment by snoop2head** [comment]
That would've been tough decision to make 😢😢😢
Works like magic now! 💯

**Comment by JaeYeopHan** [comment]
Actually, `thumbnail` was only required field for JBEE.io (https://jbee.io) :)
good luck!
