### ISSUE TITLE
Show categoryList based on existing folder

### ISSUE THREAD

**Issue by parkjihwanjay** [JaeYeopHan/gatsby-starter-bee#184]
## Description
When I run `npm run post` script, categories are still shown as default value in terminal even though I add a new category folder or change name. 

I think i'll be convenient if I can change name of category or add new category not only with script but also with GUI. 

> It's my first time to contribute to Github Project. Though I read contributing guidelines, if there is something wrong with this issue, please tell me

**Comment by JaeYeopHan** [comment]
@parkjihwanjay hi, you can edit the category by renaming `/content/blog` directories.

![image](https://user-images.githubusercontent.com/17924127/92719279-e116bc00-f39d-11ea-979c-347fc9cadf5e.png)
