### ISSUE TITLE
readme 수정 요청 부탁드립니다. 

### ISSUE THREAD

**Issue by KyeonginKim** [JaeYeopHan/gatsby-starter-bee#2]
gatsby 실행시 
port가 8000이 기본으로 잡히는 걸로 알고 있습니다. 

JaeYeopHan readme 설명에서는 
`# open localhost:8080`

로 적어 두셨더라구요. 

그리고 실제 적용해서 실행해 보니 8000으로 실행되구요.

수정 부탁드립니다. ^^

**Comment by JaeYeopHan** [comment]
@KyeonginKim 제보 감사합니다!! 수정했습니다~
