### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dongwoo-seo** [JaeYeopHan/gatsby-starter-bee#219]
## Description
![image](https://user-images.githubusercontent.com/76201181/103082738-2940ae00-461e-11eb-9aa6-ec969cc8efe3.png)

Error #11331이 발생합니다 ㅠㅠ

**Comment by JaeYeopHan** [comment]
please, follow common issue template
https://github.com/TalAter/open-source-templates/blob/master/ISSUE_TEMPLATE.md
