### ISSUE TITLE
설치 중 lighthousebot 받는 과정에서 404 에러가 나네요.

### ISSUE THREAD

**Issue by awesomeo184** [JaeYeopHan/gatsby-starter-bee#249]
## Description

![3F6C4ADD-25B2-489F-B31A-21738DAA012B](https://user-images.githubusercontent.com/63030569/114599645-56e55c00-9cce-11eb-8937-8aa4aa4a8157.png)

이것과 관련이 있을지 모르겠지만 찾아보니 lighthousebot이 deprecated 되었네요.(https://github.com/GoogleChromeLabs/lighthousebot)

이 경우에는 어떻게 해야할런지요..

**Comment by alycolbar** [comment]
I have the same problem :(

**Comment by hexdrinker** [comment]
저는 package.json, package-lock.json에서 lighthousebot 관련된 것들 다 지워줬습니다...

**Comment by JaeYeopHan** [comment]
thanks, resolved: https://github.com/JaeYeopHan/gatsby-starter-bee/pull/260
