### ISSUE TITLE
netlify build 중 node-sass error 문제에 대한 질문입니다.

### ISSUE THREAD

**Issue by gup97** [JaeYeopHan/gatsby-starter-bee#284]
## Description
이 [블로그](https://delivan.dev/web/start-gatsby-blog)에서 도움을 받던 중
netlify bulid 에서 `npm ERR! path /opt/build/repo/node_modules/node-sass` 
라는 에러메시지가 출력되었습니다. 

밑의 코드블럭과 같은 방법으로 해결하였지만,
~~~
npm uninstall node-sass
npm install sass-loader
npm install sass
~~~
제가 _놓친게 있는지, 또 이게 옳은 방법인지_ 궁금하여 질문 드립니다.

**Comment by JaeYeopHan** [comment]
this issue is related with this: #283
