### ISSUE TITLE
타이틀 바 github image 클릭 시 github 계정 주소 변경 문의

### ISSUE THREAD

**Issue by KyeonginKim** [JaeYeopHan/gatsby-starter-bee#3]
안녕하세요 ^^
gatsby-starter-bee theme 적용, 설정 하던 중 질문이 있어서 문의 드립니다. 

타이틀 바 GitHub image 클릭 시 Github 계정 주소 변경을 하고 싶은데 
gatsby-meta-config.js 에서 제공하는 설정 값 중에서는 제공하지 않는것 같아서 

혹시 어디서 설정을 해야하는지, 직접 코드를 고쳐야 하는 거면 어디서 고쳐야 하는지 문의 드립니다. 
 
감사합니다.

**Comment by KyeonginKim** [comment]
my-blog-starter/src/components/social-share/github-icon/index.jsx
에 있어서 주소가 그대로 적혀 있어서 수정 했습니다. ^^

**Comment by JaeYeopHan** [comment]
말씀하신 부분도 meta-config.js에 빼두면 좋겠네요! 의견 감사합니다!
