### ISSUE TITLE
Resolve non-ratin language issue

### ISSUE THREAD

**Issue by JaeYeopHan** [JaeYeopHan/gatsby-starter-bee#36]
## Description

- https://github.com/gatsbyjs/gatsby/issues/6916
- https://github.com/epeli/underscore.string

To resolve non-ratin language issue

**Comment by SoYoung210** [comment]
## Ref
https://www.gatsbyjs.org/packages/gatsby-transformer-remark/#excerpts-for-non-latin-languages
