### ISSUE TITLE
light/dark mode persist issue

### ISSUE THREAD

**Issue by JaeYeopHan** [JaeYeopHan/gatsby-starter-bee#46]
## Description

The theme mode is not maintained when refreshing except `jbee.io`

**Comment by snoop2head** [comment]
This happens to my site also :( 
When the site is refreshed, then dark/light theme is switched back to the light theme again.
https://noopy.dev/

**Comment by snoop2head** [comment]
@JaeYeopHan 
I opened the PR #169 to fix the issue!
