### ISSUE TITLE
blog-post 파일 수정 관련

### ISSUE THREAD

**Issue by gracieuxyh** [JaeYeopHan/gatsby-starter-bee#53]
## Description

template 폴더 아래의 blog-post.js를 수정하면 코드가 변하는데 이를 해결할 방법은 없을까요?
![스크린샷 2019-08-20 오전 9 01 20](https://user-images.githubusercontent.com/30437680/63307507-9311bf00-c329-11e9-9784-0e786ec89eb4.png)

**Comment by JaeYeopHan** [comment]
@gracieuxyh 님, 안녕하세요! fixOnSave option이 true로 되어 있으면서 eslint가 동작해서 발생하는 것 같은데요, 해당 옵션을 false로 바꿔보세요!

https://github.com/JaeYeopHan/gatsby-starter-bee/blob/master/.vscode/settings.json#L2
