### ISSUE TITLE
anchor 태그 클릭 시, smooth scroll 관련

### ISSUE THREAD

**Issue by ChanGrea** [JaeYeopHan/gatsby-starter-bee#60]
## Description
안녕하세요~ 템플릿 잘 사용하고 있습니다! 감사합니다.
큰 버그는 아니지만 포스팅 작성하다가 약간 거슬리는 부분이 있어서 사실 어디를 고쳐야 할지 잘 몰라서 올려봅니다...

포스트에서 \<h2\>, \<h3\>, \<h4\> 태그 옆에 있는 고리 모양의 anchor 클릭 시 smooth scroll 이벤트가 발생하면서 해당 위치로 부드럽게 이동합니다.

하지만 태그 안의 텍스트가 영문일 때는 문제 없지만, 한글일 경우에 해당 이벤트가 발생하지 않는 것 같습니다.

**크롬 개발자 도구 확인해보니, 한글일 경우 anchor 태그 href가 h태그 id와 일치하지 않아서 그런 것 같습니다.**

컴파일 되면서 한글이 변환되는 것 같은데... 어디를 고쳐야 할 지 잘 모르겠네요

같이 고민해봤으면 좋겠습니다!!

**Comment by JaeYeopHan** [comment]
Thanks for reporting the issue! I'll check the plugin using :)

**Comment by JaeYeopHan** [comment]
![test](https://user-images.githubusercontent.com/17924127/84588241-acf43380-ae60-11ea-811d-726145842746.gif)

현재 문제없는 것 같은데 확인 한번 해주세요~
