### ISSUE TITLE
Cannot use target blank link.

### ISSUE THREAD

**Issue by cptbong** [JaeYeopHan/gatsby-starter-bee#98]
## Description
When I wanna use a new tab link in markdown, I usually used target=_blank
ex. 
[**Google**](https://www.google.com){:target="_blank"}

but, this starter show Google{:target=“_blank”}
Can I use target blank?

**Comment by JaeYeopHan** [comment]
@cptbong  hi, you can use this:

### Working

```md
<a href="https://google.com" target="_blank">Google</a>
```

#### Not working

`[Google]( ... )`

currently, remark plugin not supporting to `[Google](https://google.com}`

**Comment by cptbong** [comment]
@JaeYeopHan 
Thanks
